# Generated by Django 3.2.5 on 2021-07-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='diasEstancia',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
